uio() API
[Synesis Software UNIX Emulation for Win32]
Detailed Description
UIO functions and types.
Classes
struct unixem_iovec
Defines a memory vector.
Defines
#define iovec unixem_iovec
Defines a memory vector.
Typedefs
typedef unixem_ssize_t ssize_t
Signed size type.
typedef signed long unixem_ssize_t
Signed size type.
Functions
ssize_t readv (int fd, struct iovec const *vector, int count)
Reads from a file into a set of memory blocks.
ssize_t writev (int fd, struct iovec const *vector, int count)
Writes to a file from a set of memory blocks.
unixem_ssize_t unixem_readv (int fd, struct unixem_iovec const *vector, int count)
Reads from a file into a set of memory blocks.
unixem_ssize_t unixem_writev (int fd, struct unixem_iovec const *vector, int count)
Writes to a file from a set of memory blocks.
Define Documentation
#define iovec unixem_iovec
Defines a memory vector.
Typedef Documentation
typedef unixem_ssize_t ssize_t
Signed size type.
typedef signed long unixem_ssize_t
Signed size type.
Function Documentation
ssize_t readv (int fd, struct iovec const * vector, int count)
Reads from a file into a set of memory blocks.
Parameters:
fd The file from which to read
vector pointer to the first element in the vector
count the number of elements in the vector
Note:
This is a macro, which resolves to unixem_readv()
unixem_ssize_t unixem_readv (int fd, struct unixem_iovec const * vector, int count)
Reads from a file into a set of memory blocks.
Parameters:
fd The file from which to read
vector pointer to the first element in the vector
count the number of elements in the vector
References unixem_iovec::iov_len, unixem_internal_errno_from_Win32(), and unixem_internal_Windows_HANDLE_from_file_handle().
unixem_ssize_t unixem_writev (int fd, struct unixem_iovec const * vector, int count)
Writes to a file from a set of memory blocks.
Parameters:
fd The file to which to write
vector pointer to the first element in the vector
count the number of elements in the vector
References unixem_iovec::iov_base, unixem_iovec::iov_len, unixem_internal_errno_from_Win32(), and unixem_internal_Windows_HANDLE_from_file_handle().
ssize_t writev (int fd, struct iovec const * vector, int count)
Writes to a file from a set of memory blocks.
Parameters:
fd The file to which to write
vector pointer to the first element in the vector
count the number of elements in the vector
Note:
This is a macro, which resolves to unixem_writev()
UNIX Emulation for Win32 Libraries documentation © Synesis Software Pty Ltd, 2002-2010